"use client";
import {useEffect,useMemo,useState} from "react";
type D={id:string;name:string;country:string;countryCode:string;region:string;lat:number;lon:number;population?:number;slug:string;attractions?:string[]};
type V={id:string;title:string;channel:string;publishedAt:string;thumbnail:string;views:number};
type Day={date:string;max:number;min:number;rain:number;code:number};
type A={destination:D;weather:{days:Day[]};decisionScore:number;predictedPlaces:(D&{score:number})[]};
const icon=(c:number)=>[95,96,99].includes(c)?"⛈️":[51,53,55,61,63,65,80,81,82].includes(c)?"🌧️":[71,73,75,77,85,86].includes(c)?"❄️":[45,48].includes(c)?"🌫️":[1,2,3].includes(c)?"⛅":"☀️";
const effect=(c?:number)=>!c?"clear":[95,96,99].includes(c)?"storm":[51,53,55,61,63,65,80,81,82].includes(c)?"rain":[71,73,75,77,85,86].includes(c)?"snow":[45,48].includes(c)?"fog":"clear";
const fmtViews=(n:number)=>n>=1e6?`${(n/1e6).toFixed(n>=1e7?0:1)}M`:n>=1e3?`${(n/1e3).toFixed(n>=1e5?0:1)}K`:`${n}`;
export default function Home(){
 const[all,setAll]=useState<D[]>([]),[country,setCountry]=useState("India"),[region,setRegion]=useState("Karnataka"),[slug,setSlug]=useState("chikmagalur"),[data,setData]=useState<A|null>(null),[latest,setLatest]=useState<V[]>([]),[popular,setPopular]=useState<V[]>([]),[tab,setTab]=useState<"latest"|"popular">("latest"),[video,setVideo]=useState<V|null>(null),[err,setErr]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[fresh7,setFresh7]=useState(0);
 useEffect(()=>{fetch("/data/destinations.json").then(r=>r.json()).then((x:D[])=>{setAll(x);setLoading(false)}).catch(()=>{setErr("Destination catalogue could not be loaded.");setLoading(false)})},[]);
 const countries=useMemo(()=>Array.from(new Set(all.map(x=>x.country))).sort(),[all]);
 const regions=useMemo(()=>Array.from(new Set(all.filter(x=>x.country===country).map(x=>x.region))).filter(Boolean).sort(),[all,country]);
 const regional=useMemo(()=>all.filter(x=>x.country===country&&x.region===region).sort((a,b)=>(b.population||0)-(a.population||0)),[all,country,region]);
 const shown=useMemo(()=>regional.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())).slice(0,80),[regional,query]);
 const days=data?.weather.days||[],past=days.slice(0,7),future=days.slice(7),today=future[0],fx=effect(today?.code);
 const rainNext=future.reduce((a,d)=>a+d.rain,0),rainPast=past.reduce((a,d)=>a+d.rain,0),rainy=future.filter(d=>d.rain>=2).length;
 const best=future.slice().sort((a,b)=>(a.rain-b.rain)||(Math.abs(a.max-26)-Math.abs(b.max-26)))[0];
 const comfort=future.length?Math.round(future.reduce((a,d)=>a+Math.max(0,100-Math.abs(d.max-26)*4-Math.min(d.rain*5,45)),0)/future.length):0;
 const current=tab==="latest"?latest:popular;
 async function load(s:string){setLoading(true);setSlug(s);setVideo(null);setErr("");const p=all.find(x=>x.slug===s);try{const[d,v]=await Promise.all([fetch(`/api/destination?slug=${encodeURIComponent(s)}`).then(r=>r.json()),fetch(`/api/videos?place=${encodeURIComponent(p?.name||s)}`).then(r=>r.json())]);if(d.error)throw new Error(d.error);setData(d);if(v.error){setErr(v.error);setLatest([]);setPopular([])}else{setLatest(v.latest||[]);setPopular(v.mostViewed||[]);setFresh7(v.fresh7||0)}}catch(e){setErr(e instanceof Error?e.message:"Unable to load destination")}finally{setLoading(false)}}
 useEffect(()=>{if(all.length)load(slug)},[all.length]);
 function changeCountry(c:string){setCountry(c);setQuery("");const rs=Array.from(new Set(all.filter(x=>x.country===c).map(x=>x.region))).filter(Boolean).sort();const r=rs[0]||"";setRegion(r);const p=all.filter(x=>x.country===c&&x.region===r).sort((a,b)=>(b.population||0)-(a.population||0))[0];if(p)load(p.slug)}
 function changeRegion(r:string){setRegion(r);setQuery("");const p=all.filter(x=>x.country===country&&x.region===r).sort((a,b)=>(b.population||0)-(a.population||0))[0];if(p)load(p.slug)}
 return <main>{loading&&<div className="loading"><div className="spinner"/><b>Analysing weather + traveller evidence…</b><small>Building your travel decision</small></div>}
 <header><div className="brand"><span>✦</span><div><b>WanderGuide</b><small>Weather + real-world evidence</small></div></div><div className="live"><i/> Live travel intelligence</div></header>
 <section className={`hero ${fx}`}><div className="weatherFx">{fx==="rain"&&Array.from({length:34},(_,i)=><i className="drop" key={i} style={{left:`${(i*37)%100}%`,animationDelay:`-${(i%9)*.17}s`}}/>)}{fx==="snow"&&Array.from({length:24},(_,i)=><i className="flake" key={i} style={{left:`${(i*43)%100}%`,animationDelay:`-${(i%8)*.3}s`}}>•</i>)}</div><div className="heroText"><small>SMART DESTINATION DECISION</small><h1>{data?.destination.name||"Where should you go?"}</h1><p>See the forecast and what travellers are actually seeing on the ground.</p></div><div className="heroScore"><small>WANDERGUIDE SCORE</small><strong>{data?.decisionScore??"—"}</strong><b>{(data?.decisionScore||0)>=80?"Great time to go":(data?.decisionScore||0)>=60?"Good, check conditions":"Consider another date"}</b></div></section>
 <section className="filters"><label><span>COUNTRY</span><select value={country} onChange={e=>changeCountry(e.target.value)}>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label><span>STATE / PROVINCE</span><select value={region} onChange={e=>changeRegion(e.target.value)}>{regions.map(x=><option key={x}>{x}</option>)}</select></label><label><span>FIND A PLACE</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${region}…`}/></label></section>
 <section className="places"><div className="sectionHead"><div><small>EXPLORE {region.toUpperCase()}</small><h2>Places in {region}</h2></div><span>{regional.length} destinations</span></div><div className="rail">{shown.map(p=><button className={p.slug===slug?"on":""} key={p.id} onClick={()=>load(p.slug)}>{p.name}<small>{p.region}</small></button>)}</div></section>
 <section className="insights"><div><i>📅</i><span><small>BEST DAY</small><b>{best?new Date(best.date).toLocaleDateString("en",{weekday:"long"}):"—"}</b></span></div><div><i>🌧️</i><span><small>NEXT 7 DAYS</small><b>{rainNext.toFixed(0)} mm rain</b></span></div><div><i>☔</i><span><small>RAINY DAYS</small><b>{rainy} of 7</b></span></div><div><i>🌡️</i><span><small>COMFORT</small><b>{comfort}/100</b></span></div><div><i>🎥</i><span><small>FRESH EVIDENCE</small><b>{fresh7} videos / 7d</b></span></div><div><i>↔</i><span><small>RAIN TREND</small><b>{rainNext<rainPast?"Improving":"Watch weather"}</b></span></div></section>
 <section className="predict"><div className="sectionHead"><div><small>7-DAY WEATHER RANKING</small><h2>Best predicted places in {region}</h2></div></div><div className="rankGrid">{(data?.predictedPlaces||[]).map((p,i)=><button key={p.id} onClick={()=>load(p.slug)}><span>#{i+1}</span><b>{p.name}</b><strong>{p.score}</strong><small>/100</small></button>)}</div></section>
 <div className="layout"><aside><small>LOCAL HIGHLIGHTS</small><h2>Top places to see in {data?.destination.name}</h2><ol>{(data?.destination.attractions||["Popular viewpoints","Nature & outdoor spots","Local markets","Historic landmarks"]).map(x=><li key={x}>{x}</li>)}</ol><div className="miniGraphic"><div style={{width:`${data?.decisionScore||0}%`}}/><small>Weather suitability</small></div></aside>
 <article><div className="destination"><small>WEATHER CONTEXT · PAST 7 → NEXT 7</small><h2>{data?.destination.region}, {data?.destination.country}</h2></div><div className="weather">{days.map((d,i)=><div className={i===7?"day futureStart":"day"} key={d.date}><small>{i<7?"PAST":"NEXT"}</small><b>{new Date(d.date).toLocaleDateString("en",{weekday:"short"})}</b><i>{icon(d.code)}</i><strong>{d.max}°</strong><em>{d.min}°</em><small>{d.rain} mm</small></div>)}</div>
 <section className="videos"><div className="sectionHead"><div><small>REAL-WORLD EVIDENCE</small><h2>See what {data?.destination.name} actually looks like</h2><p>Latest footage and popular destination videos. Click any card to watch here.</p></div><span className="fresh">● {fresh7} FRESH</span></div>
 <div className="tabs"><button className={tab==="latest"?"active":""} onClick={()=>setTab("latest")}>Latest 10</button><button className={tab==="popular"?"active":""} onClick={()=>setTab("popular")}>Most viewed 10</button></div>
 {err&&<div className="error">{err}</div>}{video&&<div className="playerWrap"><button onClick={()=>setVideo(null)}>× Close player</button><div className="player"><iframe src={`https://www.youtube-nocookie.com/embed/${video.id}?autoplay=1&rel=0`} title={video.title} allowFullScreen/></div></div>}
 <div className="vgrid">{current.map(v=><button className="vcard" key={v.id} onClick={()=>setVideo(v)}><div className="thumb"><img src={v.thumbnail} alt=""/><i>▶</i>{tab==="popular"&&<span>{fmtViews(v.views)} views</span>}</div><b>{v.title}</b><small>{v.channel} · {new Date(v.publishedAt).toLocaleDateString()}</small></button>)}</div>{!current.length&&!err&&!loading&&<div className="empty">No embeddable videos found for this destination.</div>}</section></article></div></main>
}